export const mockData =  [
    {
        "id": 3,
        "invoiceNumber": "810",
        "invoiceDate": "2020-12-03T13:00:00.000+00:00",
        "status": "PRINTED",
        "customerName": "demo polonious",
        "contactName": "Stuart Guthrie",
        "contactFax": "-",
        "contactEmail": "stuart@test.com",
        "billToAddressLine1": "",
        "billToAddressLine2": null,
        "billToAddressLine3": null,
        "billToAddressLine4": null,
        "billToSuburb": null,
        "billToCounty": null,
        "billToState": "VIC",
        "billToPostCode": null,
        "billToCountry": null,
        "discountPercentage": 20.250,
        "taxCode": "GST",
        "taxPercentage": 10.00,
        "amountIncludingTax": 597.41,
        "externalInvoiceId": "EEAA1234",
        "externalStatus": "TRANSFERED",
        "externalMessage": "",
        "arInvoiceLineDtos": [
            {
                "id": 13,
                "itemId": 16,
                "itemCode": "InvestigationTimes",
                "itemDescription": "Investigation Timesss",
                "lineDescription": "Investigative Timesss",
                "notes": "TaskItem:497:auditLogRecordId:97167",
                "comment": "Attended site visit at 52 Martin place Sydney.No issues found.",
                "quantity": 8.000,
                "unitPrice": 85.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 680.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 14,
                "itemId": 258,
                "itemCode": "TT",
                "itemDescription": "Travel Times",
                "lineDescription": "Travel Times",
                "notes": "TaskItem:501:auditLogRecordId:97168",
                "comment": "Attended site visit at 52 Martin place Sydney.No issues found.",
                "quantity": 2.000,
                "unitPrice": 0.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 0.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 15,
                "itemId": 436,
                "itemCode": "SocialIntelSearches",
                "itemDescription": "SocialIntelSearches",
                "lineDescription": null,
                "notes": "TaskItem:293:auditLogRecordId:97169",
                "comment": "Search result from SocialIntel",
                "quantity": 1.000,
                "unitPrice": 1.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 1.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            }
        ],
        "canSendToExternal": true
    },
    {
        "id": 4,
        "invoiceNumber": "000003",
        "invoiceDate": "2015-04-09T14:00:00.000+00:00",
        "status": "CONFIRMED",
        "customerName": "Demo Business",
        "contactName": "Stuart Guthrie",
        "contactFax": "-",
        "contactEmail": "stuart@test.com",
        "billToAddressLine1": "",
        "billToAddressLine2": null,
        "billToAddressLine3": null,
        "billToAddressLine4": null,
        "billToSuburb": null,
        "billToCounty": null,
        "billToState": "VIC",
        "billToPostCode": null,
        "billToCountry": null,
        "discountPercentage": 20.250,
        "taxCode": "GST",
        "taxPercentage": 10.00,
        "amountIncludingTax": 100.10,
        "externalInvoiceId": null,
        "externalStatus": "TRANSFERED",
        "externalMessage": null,
        "arInvoiceLineDtos": [
            {
                "id": 20,
                "itemId": 26,
                "itemCode": "Exp",
                "itemDescription": "Expense",
                "lineDescription": "Expense",
                "notes": "TaskItem:508:auditLogRecordId:98765",
                "comment": "",
                "quantity": 100.000,
                "unitPrice": 1.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 100.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            }
        ],
        "canSendToExternal": true
    },
    {
        "id": 2,
        "invoiceNumber": "000001",
        "invoiceDate": "2015-01-12T13:00:00.000+00:00",
        "status": "PRINTED",
        "customerName": "Insured Business Co.",
        "contactName": "Stuart Guthrie",
        "contactFax": "-",
        "contactEmail": "stuart@test.com",
        "billToAddressLine1": "",
        "billToAddressLine2": null,
        "billToAddressLine3": null,
        "billToAddressLine4": null,
        "billToSuburb": null,
        "billToCounty": null,
        "billToState": "VIC",
        "billToPostCode": null,
        "billToCountry": null,
        "discountPercentage": 20.250,
        "taxCode": "GST",
        "taxPercentage": 10.00,
        "amountIncludingTax": 100.10,
        "externalInvoiceId": null,
        "externalStatus": "RECONCILED",
        "externalMessage": null,
        "arInvoiceLineDtos": [
            {
                "id": 11,
                "itemId": 16,
                "itemCode": "InvestigationTime",
                "itemDescription": "Investigation Time",
                "lineDescription": "Investigative Time",
                "notes": "TaskItem:73:auditLogRecordId:95902",
                "comment": "Call Details: I made a call. ",
                "quantity": 0.100,
                "unitPrice": 85.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 8.500,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 12,
                "itemId": 256,
                "itemCode": "km",
                "itemDescription": "Mileage",
                "lineDescription": "Miles Travelled",
                "notes": "TaskItem:55:auditLogRecordId:95903",
                "comment": "Interviews as well as videos and photos of  and scene attached.",
                "quantity": 76.000,
                "unitPrice": 0.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 0.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 7,
                "itemId": 26,
                "itemCode": "Exp",
                "itemDescription": "Expense",
                "lineDescription": "Expense",
                "notes": "TaskItem:52:auditLogRecordId:95898",
                "comment": "Interviews as well as videos and photos of  and scene attached.",
                "quantity": 240.000,
                "unitPrice": 1.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 240.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 8,
                "itemId": 16,
                "itemCode": "InvestigationTime",
                "itemDescription": "Investigation Time",
                "lineDescription": "Investigative Time",
                "notes": "TaskItem:54:auditLogRecordId:95899",
                "comment": "Interviews as well as videos and photos of  and scene attached.",
                "quantity": 12.000,
                "unitPrice": 85.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 1020.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 9,
                "itemId": 20,
                "itemCode": "RepHUS",
                "itemDescription": "Report Hours",
                "lineDescription": "Report Hours",
                "notes": "TaskItem:53:auditLogRecordId:95900",
                "comment": "Interviews as well as videos and photos of  and scene attached.",
                "quantity": 1.000,
                "unitPrice": 1.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 1.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            },
            {
                "id": 10,
                "itemId": 258,
                "itemCode": "TT",
                "itemDescription": "Travel Time",
                "lineDescription": "Travel Time",
                "notes": "TaskItem:57:auditLogRecordId:95901",
                "comment": "Interviews as well as videos and photos of  and scene attached.",
                "quantity": 2.000,
                "unitPrice": 0.00,
                "surcharge": 0.000,
                "lineDiscount": 0.000,
                "amount": 0.000,
                "taxAmount": 0.000,
                "taxCode": "GST",
                "taxPercentage": 10.00
            }
        ],
        "canSendToExternal": true
    }
]